imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        php:
            type: stream
            path: "%kernel.logs_dir%/php_dev.log"
            level: debug
            channels: [php]
        translation:
            type: stream
            path: "%kernel.logs_dir%/translation_dev.log"
            level: debug
            channels: [translation]
        request:
            type: stream
            path: "%kernel.logs_dir%/request_dev.log"
            level: debug
            channels: [request]
        doctrine:
            type: stream
            path: "%kernel.logs_dir%/doctrine_dev.log"
            level: debug
            channels: [doctrine]
        security:
            type: stream
            path: "%kernel.logs_dir%/security_dev.log"
            level: debug
            channels: [security]
        main:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ['!security','!request','!event','!doctrine','!translation','!php']

twig:
    base_template_class: Oro\Bundle\UIBundle\Twig\Template

oro_assetic:
    css_debug:      ~
    css_debug_all:  false

oro_message_queue:
    client:
        traceable_producer: true

#swiftmailer:
#    delivery_address: me@example.com
