<?php

namespace Elemen\Bundle\CalendarBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CalendarConfigRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class CalendarConfigRepository extends EntityRepository
{
}
