<?php

namespace Elemen\Bundle\CalendarBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Elemen\Bundle\CalendarBundle\Entity\CycleDay;
use Oro\Bundle\CalendarBundle\Entity\SystemCalendar;

/**
 * CycleDayRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class CycleDayRepository extends EntityRepository
{
    public function updateDefaultCycleDays(int $num, SystemCalendar $systemCalendar)
    {
        $cycleDays = $this->findBy(['systemCalendar' => $systemCalendar->getId()], ['priority' => 'DESC']);
        $name = 'A';
        $priority = 1;

        if (count($cycleDays) < $num && count($cycleDays) <> 0 ) {
            /** @var CycleDay $day */
            $day = current($cycleDays);
            $name = $day->getShortName();
            $priority = $day->getPriority();
            $priority++; $name++;
        }

        for ($i = count($cycleDays); $i < $num; $i++) {
            $cycleDay = new CycleDay($name,$name,$priority,$systemCalendar);
            $priority++; $name++;
            $this->getEntityManager()->persist($cycleDay);
        }
        $this->getEntityManager()->flush();

    }

    /**
     * @param $calendarId
     * @return int|null
     * @throws \Doctrine\ORM\NoResultException
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function countDays($calendarId)
    {
        if(!$calendarId) return null;

        return (int) $this->getQueryBuilder()
            ->select('COUNT(cd.id)')
            ->leftJoin('cd.systemCalendar','sc')
            ->where('sc.id = :id')
            ->setParameter('id', $calendarId)
            ->getQuery()
            ->getSingleScalarResult()
        ;

    }
    /**
     * @param $calendarId
     * @return array
     */
    public function getCycleDaysByCalendarId($calendarId)
    {
        return $this->getQueryBuilder()
            ->leftJoin('cd.systemCalendar','sc')
            ->where('sc.id = :id')
            ->setParameter('id', $calendarId)
            ->orderBy('cd.priority', 'ASC')
            ->getQuery()
            ->getResult();
    }

    /**
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getQueryBuilder()
    {
        return $this->createQueryBuilder('cd');
    }
}
